data:
  test:
    platform: bitunix
    host: api.bitunix.one
    partners_host: https://partners.bitunix.one
    partnersadmin_host: https://partnersadmin.bitunix.one
    bdadmin_host: https://bdadmin.bitunix.one
    spotAdmin_host: https://spotwebadmin.bitunix.one
    web_host: https://www.bitunix.one
    partnersadmin_account: admin
    partnersadmin_password: admin
    partner_email: gerow@126.com
    bd_email: gerow1@bitunix.io
    bd_name: gerow1
    userName: gerow.wang@bitunix.io
    password: Aa123456
    spotAdminGoogleCode: HCOHDFF5JO2GUMAC
    partnersAdminGoogleCode: ONPWZTSXZV2RVJEE
    Accept-Language: zh_CN
    userId: 148002
    couponId: 567
    # 合约交易对、开仓数量
    symbol: 1000SHIBUSDT
    amount_min: 1088
    amount_max: 1888
    # 现货币种
    spotSymbol: BTC
    # 带单主账户UID ,需要使用非合伙人体系下的uid
    traderParentUid: 65750
client:
  protocol: https
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"