data:
  test:
    Accept-Language: zh_CN
    platform: bitunix
    host: api.testa.searchalpha.xyz
    partners_host: http://partners.testa.searchalpha.xyz
    partnersadmin_host: http://partnersadmin.testa.searchalpha.xyz
    bdadmin_host: http://bdadmin.testa.searchalpha.xyz
    spotAdmin_host: http://spotwebadmin.testa.searchalpha.xyz
    featuresAdmin_host: http://futureswebadmin.testa.searchalpha.xyz
    web_host: http://www.testa.searchalpha.xyz
    userId: 68566
    #welfareWebAdmin_host: http://welfarewebadmin.testa.searchalpha.xyz
    welfareWebAdmin_host: http://spotwebadmin.testa.searchalpha.xyz
    # 体验金ID
    couponId: 5
    # 合约交易对、开仓数量
    symbol: ${__RandomEnum(1000SHIBUSDT|DOGEUSDT,symbol)}
    amount_min: 1888
    amount_max: 8888
    # 现货币种
    spotSymbol: BTC
    # 带单主账户UID ,需要使用非合伙人体系下的uid
    traderParentUid: 50686
client:
  protocol: http
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"
    Accept-Language: zh_CN