spring.groovy.template.check-template-location: false
logging:
  level:
    root: INFO
    org.apache.jmeter.util: OFF
    io.qameta.allure: OFF
    org.mongodb.driver.cluster: OFF
client:
  protocol: https
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"
    Accept-Encoding: gzip, deflate, br
    Accept-Language: zh_CN
    Accept: '*/*'
data:
  test:
    amount: 200000
    partnersadmin_account: admin
    partnersadmin_password: admin
    partner_email: gerow.wang@bitunix.io
    bd_email: gerow@bitunix.io
    bd_name: gerow
    userName: gerow.wang@bitunix.io
    password: Aa123456
    welfareAdminGoogleCode: GDKKV42BO2JHIHJZ
    spotAdminGoogleCode: GDKKV42BO2JHIHJZ
    partnersAdminGoogleCode: ONPWZTSXZV2RVJEE
    welfareUserName: gerow.wang@bitunix.io
    welfarePassword: Aa123456
    Accept-Language: zh_CN