data:
  test:
    platform: bitunix
    host: api.test.searchalpha.xyz
    partners_host: http://partners.test.searchalpha.xyz
    partnersadmin_host: http://partnersadmin.test.searchalpha.xyz
    bdadmin_host: http://bdadmin.test.searchalpha.xyz
    spotAdmin_host: http://spotwebadmin.test.searchalpha.xyz
    featuresAdmin_host: http://futureswebadmin.test.searchalpha.xyz
    welfareWebAdmin_host: http://welfarewebadmin.test.searchalpha.xyz
#    welfareWebAdmin_host: http://spotwebadmin.test.searchalpha.xyz
    web_host: http://www.test.searchalpha.xyz
    # 带单主账户UID ,需要使用非合伙人体系下的uid
    userId: 16281
    couponId: 1
    # 合约交易对、开仓数量
    symbol: ${__RandomEnum(BTCUSDT)}
    amount_min: 5
    amount_max: 10
    # 现货币种
    spotSymbol: BTC
client:
  protocol: http
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"
    Accept-Language: zh_CN