data:
  test:
    platform: bitunix
    host: api.testa.searchalpha.xyz
    partners_host: http://partners.testa.searchalpha.xyz
    partnersadmin_host: http://partnersadmin.testa.searchalpha.xyz
    bdadmin_host: http://bdadmin.testa.searchalpha.xyz
    spotAdmin_host: http://spotwebadmin.testa.searchalpha.xyz
    featuresAdmin_host: http://futureswebadmin.testa.searchalpha.xyz
    web_host: http://www.testa.searchalpha.xyz
    partnersadmin_account: admin
    partnersadmin_password: admin
    # BD账户
    bd_email: gerow@bitunix.io
    bd_name: gerow
    # BD下任意一级合伙人账户
    partner_email: gerow1718700135294@aol.com
    # 用户交易使用的uid 任意一个partner_email 的直客
    userId: 64629
    # 合约/现货后台的登录账户
    userName: gerow.wang@bitunix.io
    password: Aa123456
    spotAdminGoogleCode: GGMNJZXCIFVBO6F5
    featuresAdminGoogleCode: ZXHYKFQ6PGTM72V7
    Accept-Language: zh_CN
    # 体验金ID
    couponId: 3
    # 合约交易对、开仓数量
    symbol: 1000SHIBUSDT
    amount: ${__Random(1888,3888)}
    # 现货币种
    spotSymbol: BTC
    # 带单主账户UID
    traderParentUid: 50686
client:
  protocol: http
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"
    Accept-Language: zh_CN