data:
  test:
    platform: bitunix
    host: api.xushidaifaban.com
    partners_host: partners.xushidaifaban.com
    partnersadmin_host: partnersadmin.xushidaifaban.com
    bdadmin_host: bdadmin.xushidaifaban.com
    spotAdmin_host: spotwebadmin.xushidaifaban.com
    web_host: www.xushidaifaban.com

    welfareWebAdmin_host: welfarewebadmin.xushidaifaban.com
    userId: 1232523
    couponId: 567
    # 合约交易对、开仓数量
    symbol: XRPUSDT
    amount_min: 1888
    amount_max: 18888
    # 现货币种
    spotSymbol: ETH
    # 带单主账户UID ,需要使用非合伙人体系下的uid
    traderParentUid: 1232555