data:
  test:
    platform: bitunix
    host: api.cuikulaxiu.com
    partners_host: partners.cuikulaxiu.com
    partnersadmin_host: partnersadmin.cuikulaxiu.com
    bdadmin_host: bdadmin.cuikulaxiu.com
    spotAdmin_host: spotwebadmin.cuikulaxiu.com
    featuresAdmin_host: futureswebadmin.cuikulaxiu.com
    welfareWebAdmin_host: welfarewebadmin.cuikulaxiu.com
#    welfareWebAdmin_host: spotwebadmin.cuikulaxiu.com
    web_host: www.cuikulaxiu.com
    # 带单主账户UID ,需要使用非合伙人体系下的uid
    userId: 16281
    couponId: 1
    # 合约交易对、开仓数量
    symbol: ${__RandomEnum(MATICUSDT)}
    amount_min: 5
    amount_max: 10
    # 现货币种
    spotSymbol: BTC